return region capabilities a la VFIO
nutanix/libvfio-user pull request #187
Opened 2020-12-11 14:30 UTC by tmakatos

This patch returns region capabilities the same way VFIO does: if argsz
is not large enough then it returns only region info and sets argsz to
what it should be in order to fit the capabilities, the client then
retries with a large enough argsz. The protocol specification has been
updated as well.

Plus unit tests.

Signed-off-by: Thanos Makatos <thanos.makatos@nutanix.com>

2020-12-11 16:52 UTC, tmakatos commented
I forgot to fix the client/server sample, I'll do that in a separate commit in this PR. The existing commit in this PR can be reviewed now, it shouldn't be affected by the client/server fix.

2020-12-11 16:53 UTC, tmakatos commented
We also don't pass FDs according to the protocol specification (https://github.com/nutanix/libvfio-user/issues/188).

2020-12-14 13:42 UTC, jlevon requested changes
A couple of nits only, but could you also please check in the latest spec into docs/ or something?

2020-12-14 13:42 UTC, jlevon commented on samples/client.c
> +    size_t cap_sz UNUSED;
nit, why is this UNUSED?

2020-12-14 13:42 UTC, jlevon commented on samples/server.c
> +        { .iov_base  = (void*)0, .iov_len = 0x1000},
nits: NULL? space before the trailing }

2020-12-14 15:15 UTC, tmakatos commented on samples/client.c
> +    size_t cap_sz UNUSED;
> nit, why is this UNUSED?

accidental, will fix

2020-12-14 15:15 UTC, tmakatos commented on samples/server.c
> +        { .iov_base  = (void*)0, .iov_len = 0x1000},
fixed

2020-12-14 15:25 UTC, tmakatos commented
@jlevon fixed client/server samples, please take a look at the new commits

2020-12-14 15:26 UTC, tmakatos commented
> A couple of nits only, but could you also please check in the latest spec into docs/ or something?

It's in https://github.com/tmakatos/qemu/tree/vfio-user/v8.

2020-12-14 15:48 UTC, jlevon approved these changes

2020-12-14 15:49 UTC, jlevon commented
I know it's in the qemu branch, I'm suggesting it could easily live here as the official place, at least until it's merged. It's also useful as we change the code for the spec, to see the spec change at the same time.

2020-12-14 15:50 UTC, tmakatos commented
> I know it's in the qemu branch, I'm suggesting it could easily live here as the official place, at least until it's merged. It's also useful as we change the code for the spec, to see the spec change at the same time.

Sure will add it.

2020-12-14 15:50 UTC, merged