implement fake guest thread in client/serverl live migration sample
nutanix/libvfio-user pull request #264
Opened 2021-01-22 21:51 UTC by tmakatos

2021-01-26 17:45 UTC, jlevon requested changes
just a couple of nits

2021-01-26 17:45 UTC, jlevon commented on samples/client.c
> +static void*
nit, "void *"

2021-01-26 17:45 UTC, jlevon commented on samples/client.c
> +        err(EXIT_FAILURE, "failed to open /dev/unrandom");
nit, "urandom"

2021-01-27 08:57 UTC, tmakatos commented on samples/CMakeLists.txt
> +target_link_libraries(client json-c pthread ssl crypto)
ok

2021-01-27 09:01 UTC, tmakatos commented on samples/CMakeLists.txt
> +target_link_libraries(client json-c pthread ssl crypto)
Actually they're provided by `libssl-dev`, which we already require.

2021-01-27 09:02 UTC, tmakatos commented on samples/client.c
> +static void*
ok

2021-01-27 09:02 UTC, tmakatos commented on samples/client.c
> +        err(EXIT_FAILURE, "failed to open /dev/unrandom");
ok

2021-01-27 10:35 UTC, jlevon approved these changes

2021-01-27 10:36 UTC, merged