support live migration in GPIO sample
nutanix/libvfio-user pull request #324
Opened 2021-02-10 09:20 UTC by tmakatos

2021-02-15 17:11 UTC, jlevon requested changes
just a couple of nits

2021-02-15 17:11 UTC, jlevon commented on samples/gpio-pci-idio-16.c
> +migration_get_pending_bytes(vfu_ctx_t *vfu_ctx __attribute__((unused)))
nit, here, elsewhere: use UNUSED?

2021-02-15 17:11 UTC, jlevon commented on samples/gpio-pci-idio-16.c
> +    assert (offset == 0 && size == sizeof(pin));
nit, spurious space

2021-02-15 17:11 UTC, jlevon commented on samples/gpio-pci-idio-16.c
> +    assert (offset == 0 && size == sizeof(pin));
let's separate out the two asserts too

2021-02-15 17:11 UTC, jlevon commented on samples/gpio-pci-idio-16.c
> +    assert(offset == 0 && size == sizeof(pin));
ditto

2021-02-16 09:55 UTC, tmakatos commented on samples/gpio-pci-idio-16.c
> +migration_get_pending_bytes(vfu_ctx_t *vfu_ctx __attribute__((unused)))
ok

2021-02-16 09:58 UTC, tmakatos commented on samples/gpio-pci-idio-16.c
> +    assert (offset == 0 && size == sizeof(pin));
ok

2021-02-16 11:29 UTC, jlevon approved these changes

2021-02-16 11:37 UTC, merged