don't call user's unmap_dma callback when removing DMA region
nutanix/libvfio-user pull request #370
Opened 2021-02-25 10:08 UTC by tmakatos

Plus unit tests.

Signed-off-by: Thanos Makatos <thanos.makatos@nutanix.com>
Reported-by: Changpeng Liu <changpeng.liu@intel.com>

2021-02-26 16:24 UTC, jlevon requested changes

2021-03-01 08:54 UTC, tmakatos commented on lib/libvfio-user.c
> +        if (ret < 0) { /* FIXME this if will never be taken */
sure will remove it

2021-03-01 08:54 UTC, tmakatos commented on lib/libvfio-user.c
> +        if (map && vfu_ctx->map_dma != NULL) {
good point

2021-03-01 10:35 UTC, jlevon approved these changes
just 3 tiny nits

2021-03-01 10:35 UTC, jlevon commented on test/unit-tests.c
> +        .map_dma = (void*)0xcafebabe,
nits here, below

void *

2021-03-01 11:19 UTC, merged

2021-03-01 11:24 UTC, swapnili reviewed
The commit message should say 'map_dma callback'?

2021-03-01 11:26 UTC, tmakatos commented
> The commit message should say 'map_dma callback'?

Correct, the commit message is wrong, unfortunately I just merged it :/