Fix make CFLAGS="-DNDEBUG" fail
nutanix/libvfio-user pull request #563
Opened 2021-06-09 20:29 UTC by awarus

Redefining NDEBUG in files where assert.h is included to prevent build fail due to -DNDEBUG flag
Fix for #341 issue
Signed-off-by: Ivan Efremov <i350300800e@gmail.com>

2021-06-09 21:34 UTC, jlevon commented
Thanks for this, but I don't think this makes sense as a change we want, thoughts @tmakatos?

2021-06-10 07:13 UTC, awarus commented
> Thanks for this, but I don't think this makes sense as a change we want, thoughts @tmakatos?	

I saw the opened issue and comment of @tmakatos. If it's not needed, then we should close the issue or specify in docs this limitation

2021-06-10 08:15 UTC, tmakatos commented
> Thanks for this, but I don't think this makes sense as a change we want, thoughts @tmakatos?

While we can't expect the user to use any kind of complication/linking flags they want, I `DNDEBUG` is a very common one so I think it's worth fixing.

2021-06-10 08:31 UTC, jlevon commented
The problem is that NDEBUG has a very specific meaning: disable assertions. But we don't - and shouldn't - support doing that. We always build with assertions on. So it doesn't make sense to support it.

And this version - which basically just ignores the requested CFLAGS - doesn't seem right either.

2021-06-10 09:59 UTC, awarus commented
> The problem is that NDEBUG has a very specific meaning: disable assertions. But we don't - and shouldn't - support doing that. We always build with assertions on. So it doesn't make sense to support it.
> 
> And this version - which basically just ignores the requested CFLAGS - doesn't seem right either.

Do you mean something like just a sanity check of CFLAGS in Makefile before building the project and some message that DNDEGUB force disabled?

2021-06-10 10:35 UTC, jlevon commented
Sure, we could do something like that if you like.

2021-06-10 10:59 UTC, jlevon requested changes

2021-06-10 10:59 UTC, jlevon commented on Makefile
> +	$(error -DNDEBUG flag is not support)
nit, this should say "supported"

2021-06-10 11:13 UTC, awarus commented on Makefile
> +	$(error -DNDEBUG flag is not support)
Yeah, sure

2021-06-10 13:12 UTC, jlevon approved these changes

2021-06-10 13:13 UTC, merged